Below, create a list in Python that has 5 elements (i.e. [0,1,2,3,4]) and assign it to the variable py_list.

Next, do the same, but instead of a list, create a range with 5 elements and assign it to the variable, py_range.

Finally, use the list and range to create NumPy arrays and assign the array from list to the variable array_from_list, and the array from the range to the variable array_from_range.

In [9]:
import numpy as np
py_list = [0,1,2,3,4]
py_range = range(0,5)
array_from_list = np.array(py_list)
array_from_range = np.array(py_range)

Next, we have a list of heights and weights and we'd like to use them to create a collection of BMIs. However, they are both in inches and pounds (imperial system), respectively.

Let's use what we know to create NumPy arrays with the metric equivalent values, (height in meters & weight in kg).

In [11]:
# use the conversion rate for turning height in inches to meters
list_height_inches = [65, 68, 73, 75, 78]

#Your code here
array_height_inches = np.array(list_height_inches)
array_height_meters = array_height_inches * 0.0254

In [12]:
# use the conversion rate for turning weight in pounds to kilograms
list_weight_pounds = [150, 140, 220, 205, 265]

#your code here
array_weight_pounds = np.array(list_weight_pounds)
array_weight_kg = array_weight_pounds / 2.2046

The metric formula for calculating BMI is as follows:

BMI = weight (kg) ÷ height^2 (m^2)

So, to get BMI we divide weight by the squared value of height. For example, if i weighed 130kg and was 1.9 meters tall, the calculation would look like:

BMI = 130 / (1.9*1.9)

Use the BMI calculation to create a NumPy array of BMIs

In [13]:
BMI_array = array_weight_kg / (array_height_meters * array_height_meters)

In [14]:
BMI_array

array([24.9613063 , 21.28692715, 29.02550097, 25.62324316, 30.62382485])

In [15]:
identity = np.ones(len(BMI_array))
identity

array([1., 1., 1., 1., 1.])

In [16]:
BMI_array * identity

array([24.9613063 , 21.28692715, 29.02550097, 25.62324316, 30.62382485])